const BIOFILM_CONFIG = {
    BASE_RADIUS: 25,
    MIN_SIZE_MODIFIER: 0.5,
    MAX_SIZE_MODIFIER: 1.5,
    
    MIN_HARVESTING_TIME_MS: 5000,
    MAX_HARVESTING_TIME_MS: 12000,
    
    DESPAWN_TIME_MULTIPLIER: 1.5,
    
    INITIAL_SPAWN_CHANCE: 0.01,
    SPAWN_CHANCE_INCREMENT: 0.01,
    SPAWN_INTERVAL_MS: 1000,
    
    BORDER_SAFETY_MULTIPLIER: 1.5,
    
    BASE_COLOR: '#8B4513',
    STROKE_COLOR: '#654321',
    STROKE_WIDTH: 3,
    
    SHAKE_INTENSITY_MAX: 2,
    SHRINK_COMPLETION_PERCENTAGE: 0.5,
    
    RESOURCE_TYPES_COUNT: 3
};

window.BIOFILM_CONFIG = BIOFILM_CONFIG;