const GAME_CONFIG = {
    PROJECTILE_DAMAGE: 10,
    PROJECTILE_SPEED: 8,
    
    PLAYER_MAX_ENERGY: 100,
    ENERGY_REGEN_RATE: 1,
    ENERGY_REGEN_INTERVAL_MS: 100,
    
    CORE_START_HP: 3,
    CORE_MAX_HP: 3,
    
    PULSATE_DURATION_FRAMES: 15,
    PULSATE_MAGNITUDE: 0.2,
    
    SCREEN_SHAKE_MAGNITUDE: 8,
    SCREEN_SHAKE_DURATION_FRAMES: 20,
    
    COLOR_CREAM: '#F5F5DC',
    COLOR_DARK_BLUE: '#2c3e50',
    COLOR_ENEMY_HP: '#FF6B6B',
    COLOR_INSUFFICIENT_ENERGY: '#E74C3C'
};

window.GAME_CONFIG = GAME_CONFIG;