const INTENSITY_CONFIG = {
    INITIAL_KILLCOUNT_REQUIREMENT: 3,
    KILLCOUNT_SCALING_FACTOR: 1.5,
    HP_EXPONENTIAL_BASE: 0.25,
    SPAWN_CHANCE_MODIFIER_PER_LEVEL: 0.05,
    SPAWN_GROUP_LEVEL_INTERVAL: 4,
    MAX_INTENSITY_LEVEL: 999,
    
    GAUGE_SIZE_MULTIPLIER: 2.5,
    FONT_SCALE_RATIO: 0.4
};

window.INTENSITY_CONFIG = INTENSITY_CONFIG;