const INTENSITY_CONFIG = {
    INITIAL_KILLCOUNT_REQUIREMENT: 3,
    KILLCOUNT_SCALING_FACTOR: 1.5,
    HP_MODIFIER_PER_LEVEL: 0.1,
    SPAWN_CHANCE_MODIFIER_PER_LEVEL: 0.05,
    MAX_INTENSITY_LEVEL: 999,
    
    GAUGE_SIZE_MULTIPLIER: 3,
    FONT_SCALE_RATIO: 0.4
};

window.INTENSITY_CONFIG = INTENSITY_CONFIG;