const PATHOGEN_SYSTEM_CONFIG = {
    SELECTION_TIMER_INTERVAL_MS: 120000,
    MAX_ACTIVE_SLOTS: 3,
    INITIAL_MICROBE_SELECTION_CHANCE: 1.0,
    MICROBE_SELECTION_CHANCE_DECREMENT: 0.1,
    PATHOGEN_CONTACT_DAMAGE_PERCENTAGE: 0.1,
    MINIMUM_CONTACT_DAMAGE: 1
};

const ENEMY_CATEGORIES = {
    MICROBE: 'MICROBE',
    PATHOGEN: 'PATHOGEN'
};

window.PATHOGEN_SYSTEM_CONFIG = PATHOGEN_SYSTEM_CONFIG;
window.ENEMY_CATEGORIES = ENEMY_CATEGORIES;