const PHENOTYPE_CONFIGS = {
    PERFORIN_PULSE: {
        name: 'Perforin Pulse',
        base_damage: 10,
        damage_per_level: 2,
        base_cooldown_ms: 1000,
        projectile_speed: 8,
        projectile_radius: 4,
        gauge_color_primary: '#FFE135',
        gauge_color_secondary: '#FFF176'
    }
};

const PHENOTYPE_TYPES = {
    PERFORIN_PULSE: 'PERFORIN_PULSE'
};

const PHENOTYPE_UI_CONFIG = {
    COOLDOWN_GAUGE_GAP: 10,
    COOLDOWN_GAUGE_THICKNESS_REDUCTION: 4,
    COOLDOWN_GAUGE_LINE_WIDTH: 6,
    FADE_TRANSITION_SPEED: 0.15,
    ERROR_BLINK_DURATION_FRAMES: 30,
    ERROR_BLINK_INTERVAL_FRAMES: 5
};

const PHENOTYPE_GAMEPLAY_CONFIG = {
    DEFAULT_PHENOTYPE_LEVEL: 0,
    MAX_PHENOTYPE_LEVEL: 999,
    CYTOKINE_DAMAGE_PERCENT_PER_UNIT: 0.005
};

window.PHENOTYPE_CONFIGS = PHENOTYPE_CONFIGS;
window.PHENOTYPE_TYPES = PHENOTYPE_TYPES;
window.PHENOTYPE_UI_CONFIG = PHENOTYPE_UI_CONFIG;
window.PHENOTYPE_GAMEPLAY_CONFIG = PHENOTYPE_GAMEPLAY_CONFIG;