const RESOURCE_CONFIG = {
    CYTOKINE_DROP_CHANCE: 0.75,
    CYTOKINE_HP_THRESHOLD: 10,
    ADJUVANT_DROP_CHANCE: 0.50,
    ADJUVANT_HP_THRESHOLD: 20,
    BIOMASS_DROP_CHANCE: 0.50,
    BIOMASS_HP_THRESHOLD: 10,
    
    PARTICLE_LIFESPAN_MS: 10000,
    GRAVITATION_DISTANCE: 128,
    GRAVITATION_SPEED: 4,
    
    PARTICLE_SIZE: 6,
    CYTOKINE_COLOR: '#FF6B6B',
    ADJUVANT_COLOR: '#4ECDC4',
    BIOMASS_COLOR: '#45B7D1',
    
    CYTOKINE_DAMAGE_FACTOR: 0.5,
    ADJUVANT_DENOMINATOR: 200,
    
    UI_FEEDBACK_DURATION_MS: 500
};

const RESOURCE_TYPES = {
    CYTOKINES: 'CYTOKINES',
    ADJUVANTS: 'ADJUVANTS',
    BIOMASS: 'BIOMASS'
};

const RESOURCE_NAMES = {
    CYTOKINES: 'CYT',
    ADJUVANTS: 'ADJ',
    BIOMASS: 'BIO'
};

window.RESOURCE_CONFIG = RESOURCE_CONFIG;
window.RESOURCE_TYPES = RESOURCE_TYPES;
window.RESOURCE_NAMES = RESOURCE_NAMES;